package ec.gob.sri.ws.consultas;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.2
 * 2025-06-20T21:44:33.201-05:00
 * Generated source version: 4.1.2
 *
 */
@WebServiceClient(name = "ConsultaComprobanteService",
                  wsdlLocation = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/ConsultaComprobante?wsdl",
                  targetNamespace = "http://ec.gob.sri.ws.consultas")
public class ConsultaComprobanteService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://ec.gob.sri.ws.consultas", "ConsultaComprobanteService");
    public static final QName ConsultaComprobantePort = new QName("http://ec.gob.sri.ws.consultas", "ConsultaComprobantePort");
    static {
        URL url = null;
        try {
            url = URI.create("https://cel.sri.gob.ec/comprobantes-electronicos-ws/ConsultaComprobante?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaComprobanteService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://cel.sri.gob.ec/comprobantes-electronicos-ws/ConsultaComprobante?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaComprobanteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaComprobanteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaComprobanteService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultaComprobanteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaComprobanteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaComprobanteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultaComprobante
     */
    @WebEndpoint(name = "ConsultaComprobantePort")
    public ConsultaComprobante getConsultaComprobantePort() {
        return super.getPort(ConsultaComprobantePort, ConsultaComprobante.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaComprobante
     */
    @WebEndpoint(name = "ConsultaComprobantePort")
    public ConsultaComprobante getConsultaComprobantePort(WebServiceFeature... features) {
        return super.getPort(ConsultaComprobantePort, ConsultaComprobante.class, features);
    }

}
