
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ec.gob.sri.ws.consultas;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.2
 * 2025-06-20T21:44:33.191-05:00
 * Generated source version: 4.1.2
 *
 */

@jakarta.jws.WebService(
                      serviceName = "ConsultaComprobanteService",
                      portName = "ConsultaComprobantePort",
                      targetNamespace = "http://ec.gob.sri.ws.consultas",
                      wsdlLocation = "https://cel.sri.gob.ec/comprobantes-electronicos-ws/ConsultaComprobante?wsdl",
                      endpointInterface = "ec.gob.sri.ws.consultas.ConsultaComprobante")

public class ConsultaComprobantePortImpl implements ConsultaComprobante {

    private static final Logger LOG = Logger.getLogger(ConsultaComprobantePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ec.gob.sri.ws.consultas.ConsultaComprobante#consultarEstadoAutorizacionComprobante(java.lang.String claveAcceso)*
     */
    public ec.gob.sri.ws.consultas.RespuestaConsultaComprobante consultarEstadoAutorizacionComprobante(java.lang.String claveAcceso) throws IllegalArgumentException_Exception   {
        LOG.info("Executing operation consultarEstadoAutorizacionComprobante");
        System.out.println(claveAcceso);
        try {
            ec.gob.sri.ws.consultas.RespuestaConsultaComprobante _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IllegalArgumentException_Exception("IllegalArgumentException...");
    }

}
