package ec.gob.sri.ws.consultas;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.2
 * 2025-06-20T21:44:33.198-05:00
 * Generated source version: 4.1.2
 *
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.consultas", name = "ConsultaComprobante")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaComprobante {

    @WebMethod
    @RequestWrapper(localName = "consultarEstadoAutorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.consultas", className = "ec.gob.sri.ws.consultas.ConsultarEstadoAutorizacionComprobante")
    @ResponseWrapper(localName = "consultarEstadoAutorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.consultas", className = "ec.gob.sri.ws.consultas.ConsultarEstadoAutorizacionComprobanteResponse")
    @WebResult(name = "EstadoAutorizacionComprobante", targetNamespace = "")
    public ec.gob.sri.ws.consultas.RespuestaConsultaComprobante consultarEstadoAutorizacionComprobante(

        @WebParam(name = "claveAcceso", targetNamespace = "")
        java.lang.String claveAcceso
    ) throws IllegalArgumentException_Exception;
}
